{% set name = "vina" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccsb-scripps/AutoDock-Vina/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6778b28ffc7c70dde81e8fdf5dbe415f3da9c65451eeb92623991082b31fc8b0
  patches:
    - vina.patch


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - swig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - libboost-devel <=1.84
    - python
    - pip
    - setuptools
  run:
    - numpy
    - python

test:
  imports:
    - vina
  commands:
    - vina --help
    - vina_split --help

about:
  home: http://vina.scripps.edu
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Docking and virtual screening program
  description: |
    AutoDock Vina is one of the fastest and most widely used open-source
    docking engines. It is a turnkey computational docking program that
    is based on a simple scoring function and rapid gradient-optimization
    conformational search.
  doc_url: https://autodock-vina.readthedocs.io/
  dev_url: https://github.com/ccsb-scripps/AutoDock-Vina/

extra:
  recipe-maintainers:
    - joanimato
    - rwxayheee
    - diogomart
    - simonbray
