{% set name = "vina" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccsb-scripps/AutoDock-Vina/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 22f85b2e770b6acc363429153b9551f56e0a0d88d25f747a40d2f55a263608e0
  patches:
    - vina.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - swig
  host:
    - boost-cpp
    - python
    - pip
  run:
    - boost-cpp
    - numpy
    - openbabel
    - python

test:
  imports:
    - vina
  commands:
    - vina --help
    - vina_split --help

about:
  home: http://vina.scripps.edu
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Docking and virtual screening program
  description: |
    AutoDock Vina is one of the fastest and most widely used open-source
    docking engines. It is a turnkey computational docking program that
    is based on a simple scoring function and rapid gradient-optimization
    conformational search.
  doc_url: https://autodock-vina.readthedocs.io/
  dev_url: https://github.com/ccsb-scripps/AutoDock-Vina/

extra:
  recipe-maintainers:
    - simonbray
