{% set name = "vina" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccsb-scripps/AutoDock-Vina/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9b7068eac53e47a441163586f4624730ea7e319841752e8ccee9ea37ac63fcec
  patches:
    - vina.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - swig
  host:
    - boost-cpp
    - python
    - pip
  run:
    - boost-cpp
    - numpy
    - openbabel
    - python

test:
  imports:
    - vina
  commands:
    - vina --help
    - vina_split --help

about:
  home: http://vina.scripps.edu
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Docking and virtual screening program
  description: |
    AutoDock Vina is one of the fastest and most widely used open-source
    docking engines. It is a turnkey computational docking program that
    is based on a simple scoring function and rapid gradient-optimization
    conformational search.
  doc_url: https://autodock-vina.readthedocs.io/
  dev_url: https://github.com/ccsb-scripps/AutoDock-Vina/

extra:
  recipe-maintainers:
    - simonbray
